from typing import Protocol


class ConsoleAdapter(Protocol):
    def start_url(self) -> str: ...
    def read_tools(self) -> list[str]: ...
    def write_tool(self) -> str: ...
    def action_for(self, remediation: str) -> dict: ...
    def investigation_brief(self, task: str) -> str: ...
